// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrfyhonhsrdhxmayztzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhyZnlob25oc3JkaHhtYXl6dHp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwODM4MjYsImV4cCI6MjA2NTY1OTgyNn0.mpQSq4GXRu1CKGLjIKqF5JQkDpgTO5JPMZuI9sgq0gQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);